FROM agaveapi/torque:latest

ARG CYLC_SSH_PUBKEY
RUN if [[ ! ${CYLC_SSH_PUBKEY} == ssh-* ]]; then echo "Need to set CYLC_SSH_PUBKEY" && exit 1; fi

RUN yum groupinstall -y "development-tools"

RUN yum install -y \
        at \
        git \
        pkgconfig \
        python python-devel python-pip \
        python-setuptools \
        python-empy \
        python-urllib3 \
        pyOpenSSL \
        rsync \
        sqlite \
        time \
        ; yum clean all

RUN mkdir /home/testuser/.cylc && chown testuser: /home/testuser/.cylc

# Add Cylc utilities to the PATH environment variable

ENV PATH="/opt/cylc/bin:/usr/bin/:${PATH}"
COPY cylc/usr/bin/cylc /home/testuser/bin/cylc

RUN chown -R testuser: /home/testuser/bin \
    && chmod 0755 /home/testuser/bin/cylc

# Copy SSH keys

RUN echo "${CYLC_SSH_PUBKEY}" >> /home/testuser/.ssh/authorized_keys

RUN chown -R testuser: /home/testuser/.ssh/ \
    && chmod 0700 /home/testuser/.ssh/ \
    && chmod 0644 /home/testuser/.ssh/authorized_keys

USER testuser
RUN mkdir /home/testuser/cylc-run
VOLUME ["/home/testuser/cylc-run"]

USER root

# In docker-compose we are setting the hostname to pbs. Here we just
# hint to PBS Torque that there is a node called pbs with 1 processor
# available. Otherwise it would try to use localhost and fail as
# `hostname` never returned it!
RUN echo "pbs np=1" >> /var/spool/torque/server_priv/nodes

WORKDIR /usr/local/5.0.0l
EXPOSE 10389 22
VOLUME ["/opt/cylc"]
CMD ["/usr/bin/supervisord"]
