FROM kinow/cylc-standalone:0.1

RUN apt-get update && apt-get --no-install-recommends -y install \
	inetutils-ping \
	less \
	python-empy \
	python-requests \
	ssh \
	supervisor

# Copy SSH keys

RUN adduser "testuser" --uid 500 && \
    echo "testuser:testuser" | chpasswd

COPY id_rsa /home/testuser/.ssh/id_rsa
COPY id_rsa.pub /home/testuser/.ssh/id_rsa.pub
COPY config /home/testuser/.ssh/config

RUN chown -R testuser: /home/testuser/.ssh/ \
    && chmod 0700 /home/testuser/.ssh/ \
    && chmod 0644 /home/testuser/.ssh/id_rsa.pub \
    && chmod 0600 /home/testuser/.ssh/config \
    && chmod 0600 /home/testuser/.ssh/id_rsa

VOLUME "/opt/cylc" "/tmp" "/run" "/var/run"
WORKDIR "/opt/cylc"

ENV PATH="/opt/cylc/bin:/usr/bin/:${PATH}"
COPY cylc/usr/bin/cylc /home/testuser/bin/cylc

ENTRYPOINT []
CMD ["/usr/bin/supervisord", "-n"]
